// Warm Lead Generation — data access layer.
// Wraps the shared Supabase client with helpers for warm_leads, sources, and
// settings. Same pattern as lead-os-db.ts: hand-rolled types at the function
// boundary, client cast to `any` until the auto-generated Database type is
// regenerated by Lovable.

import { supabase as sharedClient } from "@/integrations/supabase/client";
import { createLead } from "./lead-os-db";
import type {
  WarmLead,
  WarmLeadSettings,
  WarmLeadSettingsUpdate,
  WarmLeadSource,
  WarmLeadSourceId,
  WarmLeadSourceUpdate,
  WarmLeadStats,
  WarmLeadStatus,
  WarmLeadUpdate,
  WarmLeadWithSource,
} from "./warm-leads-types";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const supabase = sharedClient as any;

// ============================================================================
// Sources
// ============================================================================

export async function listWarmLeadSources(): Promise<WarmLeadSource[]> {
  const { data, error } = await supabase
    .from("warm_lead_sources")
    .select("*")
    .order("id", { ascending: true });
  if (error) throw error;
  return (data ?? []) as WarmLeadSource[];
}

export async function updateWarmLeadSource(
  id: WarmLeadSourceId,
  patch: WarmLeadSourceUpdate,
): Promise<WarmLeadSource> {
  const { data, error } = await supabase
    .from("warm_lead_sources")
    .update(patch)
    .eq("id", id)
    .select("*")
    .single();
  if (error) throw error;
  return data as WarmLeadSource;
}

// ============================================================================
// Settings (singleton row)
// ============================================================================

export async function getWarmLeadSettings(): Promise<WarmLeadSettings> {
  const { data, error } = await supabase
    .from("warm_lead_settings")
    .select("*")
    .eq("id", "singleton")
    .single();
  if (error) throw error;
  return data as WarmLeadSettings;
}

export async function updateWarmLeadSettings(
  patch: WarmLeadSettingsUpdate,
): Promise<WarmLeadSettings> {
  const { data, error } = await supabase
    .from("warm_lead_settings")
    .update(patch)
    .eq("id", "singleton")
    .select("*")
    .single();
  if (error) throw error;
  return data as WarmLeadSettings;
}

// ============================================================================
// Warm Leads — inbox queries
// ============================================================================

export async function listWarmLeads(filter?: {
  status?: WarmLeadStatus;
  sourceId?: WarmLeadSourceId;
  limit?: number;
}): Promise<WarmLeadWithSource[]> {
  let q = supabase
    .from("warm_leads_with_source")
    .select("*")
    .order("score", { ascending: false })
    .order("created_at", { ascending: false });
  if (filter?.status) q = q.eq("status", filter.status);
  if (filter?.sourceId) q = q.eq("source_id", filter.sourceId);
  if (filter?.limit) q = q.limit(filter.limit);
  const { data, error } = await q;
  if (error) throw error;
  return (data ?? []) as WarmLeadWithSource[];
}

export async function getWarmLead(id: string): Promise<WarmLeadWithSource | null> {
  const { data, error } = await supabase
    .from("warm_leads_with_source")
    .select("*")
    .eq("id", id)
    .single();
  if (error) {
    if (error.code === "PGRST116") return null;
    throw error;
  }
  return data as WarmLeadWithSource;
}

export async function updateWarmLead(
  id: string,
  patch: WarmLeadUpdate,
): Promise<WarmLead> {
  // Stamp reviewed_at on any status change away from 'new'.
  const finalPatch: Record<string, unknown> = { ...patch };
  if (patch.status && patch.status !== "new") {
    finalPatch.reviewed_at = new Date().toISOString();
  }
  const { data, error } = await supabase
    .from("warm_leads")
    .update(finalPatch)
    .eq("id", id)
    .select("*")
    .single();
  if (error) throw error;
  return data as WarmLead;
}

// ----------------------------------------------------------------------------
// Promote: turn an approved warm_lead into a real `leads` row + link back.
// Used by the "Approve & save to CRM" button in the inbox.
// ----------------------------------------------------------------------------
export async function promoteWarmLead(id: string): Promise<{
  warm_lead: WarmLead;
  lead_id: string;
}> {
  const wl = await getWarmLead(id);
  if (!wl) throw new Error("Warm lead not found");
  if (wl.promoted_lead_id) {
    return { warm_lead: wl as WarmLead, lead_id: wl.promoted_lead_id };
  }

  const display =
    wl.author_display_name?.trim() ||
    wl.author_handle?.trim() ||
    "Unknown (from " + wl.source_label + ")";

  const created = await createLead({
    name: display,
    email: null,
    phone: null,
    company: null,
    how_i_know_them: `Found via ${wl.source_label}: ${wl.url}`,
    what_they_might_need: wl.raw_title ?? wl.raw_excerpt.slice(0, 200),
    status: "warm",
    last_contact_date: null,
    next_action: wl.drafted_message
      ? "Send drafted outreach message"
      : "Reach out — see source link",
    next_action_date: new Date().toISOString().slice(0, 10),
    notes: [
      `Source: ${wl.source_label} (${wl.url})`,
      wl.score_reasoning ? `Why this is a fit: ${wl.score_reasoning}` : null,
      wl.drafted_message ? `\nDrafted outreach:\n${wl.drafted_message}` : null,
      `\nOriginal post:\n${wl.raw_excerpt}`,
    ]
      .filter(Boolean)
      .join("\n"),
  });

  const updated = await updateWarmLead(id, {
    status: "approved",
    promoted_lead_id: created.id,
  });

  return { warm_lead: updated, lead_id: created.id };
}

// ============================================================================
// Trigger the scraper edge function on demand (the "Run now" button).
// ============================================================================
export async function triggerScrapeNow(): Promise<{
  inserted: number;
  scanned: number;
  scored: number;
  errors: string[];
}> {
  const { data, error } = await supabase.functions.invoke("scrape-warm-leads", {
    body: { trigger: "manual" },
  });
  if (error) throw error;
  return (data ?? { inserted: 0, scanned: 0, scored: 0, errors: [] }) as {
    inserted: number;
    scanned: number;
    scored: number;
    errors: string[];
  };
}

// ============================================================================
// Stats
// ============================================================================
export async function getWarmLeadStats(): Promise<WarmLeadStats> {
  const since30 = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
  const since7 = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

  const [newCountQ, weekCountQ, sentWeekQ, last30Q] = await Promise.all([
    supabase
      .from("warm_leads")
      .select("*", { count: "exact", head: true })
      .eq("status", "new"),
    supabase
      .from("warm_leads")
      .select("*", { count: "exact", head: true })
      .gte("created_at", since7),
    supabase
      .from("warm_leads")
      .select("*", { count: "exact", head: true })
      .eq("status", "sent")
      .gte("reviewed_at", since7),
    supabase
      .from("warm_leads")
      .select("score, status")
      .gte("created_at", since30),
  ]);

  const rows = (last30Q.data ?? []) as { score: number; status: string }[];
  const sent = rows.filter((r) => r.status === "sent" || r.status === "converted").length;
  const converted = rows.filter((r) => r.status === "converted").length;
  const avg =
    rows.length === 0
      ? 0
      : rows.reduce((acc, r) => acc + Number(r.score ?? 0), 0) / rows.length;

  return {
    total_new: newCountQ.count ?? 0,
    total_this_week: weekCountQ.count ?? 0,
    total_sent_this_week: sentWeekQ.count ?? 0,
    conversion_rate_30d: sent === 0 ? 0 : converted / sent,
    avg_score_30d: Math.round(avg),
  };
}
